
# colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# Screen settings
ORIGINAL_TILE_SIZE = 16
SCALE = 3
TILE_SIZE = ORIGINAL_TILE_SIZE * SCALE

MAX_SCREEN_COL = 16
MAX_SCREEN_ROW = 12

SCREEN_HEIGHT = TILE_SIZE * MAX_SCREEN_ROW
SCREEN_WIDTH = TILE_SIZE * MAX_SCREEN_COL

# World settings
MAX_WORLD_COL = 50
MAX_WORLD_ROW = 50
WORLD_WIDTH = TILE_SIZE * MAX_SCREEN_COL 
WORLD_HEIGHT = TILE_SIZE * MAX_SCREEN_ROW
